export const publishUpdateMediaPayloads = {
  TestCase1: {
    id: 'EYCMiNeI',
    tags: ['trailer', 'TestCase1', 'TestCase2'],
    customParameters: { TestCase: '1', preview_playback: 'https://cdn.jwplayer.com/manifests/LqaujshZ.m3u8', plan_id: 'no' },
    expirationDate: '2099-12-31T12:00:00.000Z',
    publishDate: '2025-07-28T04:33:00.000Z',
    mediaTypeId: 7,
    network: 'en',
    externalId: 'LqaujshZ',
    trailers: [],
    adBreaks: [],
    mediaBasicInfo: [
      { id: 259522, title: 'Publish Title', description: 'Publish Description', programName: null, programId: null, language: 'en', tenantId: 4, mediaId: 'EYCMiNeI' },
    ],
    thumbnailAsset: [
      {
        mediaId: 'EYCMiNeI',
        tenantId: 4,
        thumbnailKey: 'default',
        thumbnailUrl: 'https://cdn.jwplayer.com/v2/media/LqaujshZ/poster.jpg',
        externalId: '7QHr4f5H',
        isThumbnailReuploaded: false,
        deleted: false,
        publishDate: null,
        auditInfoId: null,
        contentSource: 'EXTERNAL',
        id: 275471,
      },
    ],
    videoAsset: {
      id: 306145,
      mediaId: 'EYCMiNeI',
      tenantId: 4,
      videoKey: 'Tom & Jerry _ Best Buddies 🐭🐱🐶 _ Classic Cartoon Compilation _ WB Kids.mp4',
      videoUrl: 'https://d1gsai8h4wemh7.cloudfront.net/MBS_ASSETS/dev/videos/tom-and-jerry-_-best-buddies-_-classic-cartoon-compilation-_-wb-kids-1753679769574.mp4',
      deleted: null,
      publishDate: null,
      duration: 1758.354,
      isVideoReUploaded: true,
      contentSource: 'LOCAL',
      captions: [],
      audioTracks: [],
      videoResolutions: [],
    },
    dynamicLink: [],
  },
};
